### ISSUE TITLE
Whitelabelling configuration

### ISSUE THREAD

**Issue by igoroctaviano** [MGHComputationalPathology/slim#17]
- Header needs to be configurable through white-labeling properties e.g. Logo, Title, Description, etc.

**Comment by hackermd** [comment]
@igoroctaviano @wlongabaugh @fedorov what do we want to override for the IDC?

The logo in the browser tab is straight forward. One just needs to replace the `logo192png` file on the web server (see [index.html](https://github.com/MGHComputationalPathology/slim/blob/9f9115ed3a3efcab9b48747a06dd825f6c0bf1a6/public/index.html#L12)). The title/description in the tab could also be updated by changing the `index.html` file. Not sure whether we would need more complex configuration for this. Thoughts?

Including the logo in the app header would probably require changes to the configuration and source code. Please let me know what that should like.

**Comment by fedorov** [comment]
Markus, I do think we will need to have the logo in the app for the Sept release, same as we do in OHIF, but this can wait until after the next week's release.
