### ISSUE TITLE
setup preview for PR

### ISSUE THREAD

**Issue by Punzo** [MGHComputationalPathology/slim#19]
look into netlify as OIHF viewer

**Comment by Punzo** [comment]
Igor has done it with firebase, see https://github.com/igoroctaviano/slim/pull/3/checks?check_run_id=2621971527

**Comment by igoroctaviano** [comment]
Tested Firebase Deploy both for OHIF fork and SLIM:
- OHIF:
  - Preview: https://idc-slim--pr5-test-3wlngske.web.app/
  - PR Pipeline: https://github.com/igoroctaviano/Viewers/pull/5/checks?check_run_id=2622310885
- SLIM: 
  - Preview: https://idc-slim--pr3-test-cawctd67.web.app/
  - PR Pipeline: https://github.com/igoroctaviano/slim/pull/3/checks?check_run_id=2621971527
  
 For projects using Netlify only for deploy preview, we could just switch to Firebase Hosting.

**Comment by hackermd** [comment]
@igoroctaviano The Slim preview currently fails for me due to CORS headers.

**Comment by igoroctaviano** [comment]
> @igoroctaviano The Slim preview currently fails for me due to CORS headers.

@hackermd we decided to go with independent servers? e.g. dcmjs? which server you're using?

**Comment by pieper** [comment]
Igor can you try the server I emailed about earlier?

https://idc-external-006.uc.r.appspot.com/studies

**Comment by igoroctaviano** [comment]
> https://idc-external-006.uc.r.appspot.com/studies

@pieper just tested and its working fine. Here: https://idc-slim--pr3-test-cawctd67.web.app/
@hackermd can you use this one then?

**Comment by pieper** [comment]
Excellent, thanks Igor.

As you play with this let me know if it feels like the proxy slows it down
compared to hitting the dicomweb endpoint directly.

-Steve

**Comment by igoroctaviano** [comment]
@hackermd @pieper which google acc we are going to use to set up the preview? if there's one for slim already, you can generate the firebase config with the following steps:
- In the repo folder, run: `firebase init hosting`
- Follow the CLI prompts, and the command will automatically take care of setting up the GitHub Action. In this step, you'll need to set up the public folder to `build` and define a build/deploy script if any 
- Commit and push these changes to master 
- Done! deploy preview should be triggered on every pull request
<sub>Reference: https://firebase.google.com/docs/hosting/github-integration</sub>

**Comment by pieper** [comment]
> which google acc we are going to use

Does acc mean account?  I don't think it matters.  I believe the use case will stay in the free tier, but if there's a concern it won't then @hackermd could use an account from his idc-external-006 project.

**Comment by Punzo** [comment]
this was done by @igoroctaviano  in https://github.com/MGHComputationalPathology/slim/pull/34, closing!
