### ISSUE TITLE
How to upload WSI DICOM data to slim ?

### ISSUE THREAD

**Issue by DrexlerChao** [MGHComputationalPathology/slim#27]
Hi Guys,
I try to use docker-compose file to deploy slim on localhost. 
After install complete and connect to http://localhost:8008, then the slim show "Request to search for studies failed."
How to fix the issue and upload wsi dcm data to slim ?
Any help will be sincerely appreciate.
Thanks.

**Comment by hackermd** [comment]
The DICOMweb endpoint is exposed at http://localhost:8008/dicomweb. One can just store studies in the archive using the [Store transaction of the DICOMweb Studies Service](http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_10.5.html). I added a line to the README via 4c48bbe5be1951598a06d7a875709b86ae4d5cdc
