### ISSUE TITLE
3D Slicer DICOMweb Browser connect to slim error

### ISSUE THREAD

**Issue by DrexlerChao** [MGHComputationalPathology/slim#28]
Dear Sir,
In order to upload dcm files to slim, I try to use 3D Slicer 4.13.0 DICOMweb Browser to connect slim DICOMweb at http://localhost:8008/dicomweb .
But DICOMweb response the error message "500 Server Error: Internal Server Error for url: http://localhost:8008/dicomweb/studies?offset=0"

How to use the 3D Slicer 4.13.0 DICOMweb Browser to connect slim DICOMweb correctly ?
How to set slim config file for client to connect  DICOMweb at http://localhost:8008/dicomweb ?
Any suggestion for upload dcm file to slim ?

Thanks a lot.

**Comment by hackermd** [comment]
Thanks @DrexlerChao for testing the application and for your feedback. Unfortunately, I don't have any experience in using the 3D Slicer DICOMweb Browser and therefore can't give you any advice in this regard. Maybe @fedorov or @pieper could help?

I would recommend using the [dicomweb-client](https://github.com/MGHComputationalPathology/dicomweb-client) to upload files to the DICOMweb service. The Python package provides a command line interface that makes that task rather easy:

```none
$ pip install dicomweb-client
$ dicomweb_client -vv --url http://localhost:8008/dicomweb store instances $FILEPATH
```

**Comment by pieper** [comment]
@DrexlerChao - 3D Slicer's dicomweb implementation should be able to work with the same back end as Slim, so let us know if you ran into any troubles.  Of course Slicer doesn't have much support that is specific to WSI, so it won't understand pyramids or anything, but loading images and applying filters should work fine.

**Comment by DrexlerChao** [comment]
Thanks @hackermd for suggestion.
I use dicomweb-client to upload dcm file, but the slim response error message as follow,
$ dicomweb_client -vv --url http://localhost:8008/dicomweb store instances SM000001.dcm
then,
2021-06-08 09:12:15 | INFO     | dicomweb_client.api                      | store instances
2021-06-08 09:12:17 | INFO     | dicomweb_client.api                      | store data in chunks using chunked transfer encoding
2021-06-08 09:12:17 | ERROR    | dicomweb_client.cli                      | 500 Server Error: Internal Server Error for url: http://localhost:8008/dicomweb/studies

What are the causes of error 500? Did I miss something?

**Comment by DrexlerChao** [comment]
@pieper - I use 3D Slicer DICOMweb Browser to connect slim DICOMweb at http://localhost:8008/dicomweb.
But DICOMweb response the error message "500 Server Error: Internal Server Error for url: http://localhost:8008/dicomweb/studies?offset=0"

Slim seem like "block" client connection, while I use dicomweb-client or 3D Slicer.
How to fix the connection error? Any configuration have to set?

**Comment by pieper** [comment]
@DrexlerChao I don't know about the localhost configuration, but it makes sense that you would get the same error from both Slicer and Slim, since they are hitting the same endpoijnts.

Have you tried using a google endpoint, like the one listed [here](https://github.com/DICOMWG26AnnotationAHG/hackathon/blob/main/servers.md#dicomweb-studies-service-base-uri-2)?

**Comment by DrexlerChao** [comment]
@pieper Thanks for your suggestion.
Yes. 3D Slicer DICOMweb Browser connect to Google Cloud DICOMweb Studies Service Base URI https://idc-external-006.uc.r.appspot.com is working.

But, how to fix the localhost connection issue to upload DICOM files to the Slim DICOMweb service?
Any help or suggestion will be sincerely appreciate.
Thanks.

**Comment by pieper** [comment]
> @pieper Thanks for your suggestion.
> Yes. 3D Slicer DICOMweb Browser connect to Google Cloud DICOMweb Studies Service Base URI https://idc-external-006.uc.r.appspot.com is working.

Great!

> 
> But, how to fix the localhost connection issue to upload DICOM files to the Slim DICOMweb service?
> Any help or suggestion will be sincerely appreciate.
> Thanks.

By this I assume you mean the docker compose option that uses dcm4chee behind the scenes.  I'm afraid I can't help with that specifically since I've never used it.  Could be something like disk volume permissions or ports, but hard to say.  @hackermd do you have a recipe for a clean install, perhaps on a GCP VM?

**Comment by hackermd** [comment]
> But, how to fix the localhost connection issue to upload DICOM files to the Slim DICOMweb service?

Internal server error is an indication that there may be a problem with the docker deployment. What do the DCM4CHE server logs say? You can expect them in the container as follows:

    $ docker exec slim_arc_1 cat /opt/wildfly/standalone/log/server.log

**Comment by DrexlerChao** [comment]
@hackermd Thanks for your suggestion.
After reinstall, the Slim webviewer is working very well.
The dcm4che log file is helpful to me when I face other issue in the future.
Thanks a lot.
