### ISSUE TITLE
Extend dicom-microscopy-viewer API and SLIM to use OpticalPathUID

### ISSUE THREAD

**Issue by Punzo** [MGHComputationalPathology/slim#31]
Currently the dicom-miscroscopy-viewer and SLIM use the Optical Path Identifier to handles channels, apply the color functions, etc... However the Optical Path Identifier could not be always unique, see for more details:
https://github.com/MGHComputationalPathology/slim/issues/22#issuecomment-854642273

We should introduce a new unique DICOM attribute OpticalPathUID.

**Comment by hackermd** [comment]
Based on the discussion with @dclunie, we decided to rather clarify uniqueness requirements for the existing Optical Path Identifier attribute rather than introducing a new Optical Path UID attribute.
