### ISSUE TITLE
How to get Slim DICOM SR document ?

### ISSUE THREAD

**Issue by DrexlerChao** [MGHComputationalPathology/slim#33]
Dear Sir,
After draw and save ROI, the Slim store them as DICOM comprehensive 3D SR documents.
We use 3D Slicer DICOMweb browser to connect slim http://localhost:8008/dicomweb, the list of cases as follow,
![Screenshot from 2021-07-19 09-26-52](https://user-images.githubusercontent.com/27002631/126090507-1b168754-4b5e-4b8c-a1cb-ac00c22d3eb4.png)
We try to retrieve studies, but the 3D Slicer response the error as follow,
![Screenshot from 2021-07-21 11-42-23](https://user-images.githubusercontent.com/27002631/126451651-de0ff785-f5c1-407f-8ab2-b42150789a03.png)
Here is 3D Slicer debug message,
![Screenshot from 2021-07-21 14-47-22](https://user-images.githubusercontent.com/27002631/126451749-e4e714ed-4e15-4f01-9cfe-339def5ca982.png)

Where is the location that slim saved the DICOM files and SR documents ?
How to read/write the SR document when AI training / inference ?
Could you recommend some tools to us to use DICOM SR document ? 

Any help or suggestion will be sincerely appreciate.
Thanks a lot.

**Comment by DrexlerChao** [comment]
Dear Sir,
We use Postman API tool to GET slim study, series and instance list via 
http://localhost:8008/dicomweb/studies
http://localhost:8008/dicomweb/series
http://localhost:8008/dicomweb/instance
![Screenshot from 2021-07-19 15-49-41](https://user-images.githubusercontent.com/27002631/126124471-56811803-4284-4c4b-b93b-9ea15012e08c.png)

We are not sure the dicomweb API whether enable to GET the DICOM SR document ?

**Comment by hackermd** [comment]
The Retrieve Transaction of the DICOMweb Studies Service is specified in [part 18 section 10.4 of the DICOM standard](http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_10.4.html).

Retrieving the whole study is generally not a good idea in digital pathology, given the size of the data sets. I would recommend first searching for instances with query string `Modality=SR` and then retrieving the instances individually. You may want to take a look at DICOMweb Python client ([DICOMwebClient.search_for_instances](/https://dicomweb-client.readthedocs.io/en/latest/package.html#dicomweb_client.api.DICOMwebClient.retrieve_instance) and [DICOMwebClient.retrieve_instance](https://dicomweb-client.readthedocs.io/en/latest/package.html#dicomweb_client.api.DICOMwebClient.retrieve_instance))

**Comment by hackermd** [comment]
I am closing this issue since it's a general question about the DICOMweb standard rather than the Slim application.

**Comment by DrexlerChao** [comment]
@hackermd Dear Sir,
Thanks for your useful suggestions.
