### ISSUE TITLE
Problems hosting content with /slim in path.

### ISSUE THREAD

**Issue by wlongabaugh** [MGHComputationalPathology/slim#36]
I am trying to have SliM served up from a non-root directory, so that I can have the same hostname for the two different viewers and route traffic based on the URL. (e.g. I want https://hostname.example.com/slim/studies/blah... to go to the SliM Bucket, and other paths to go to radiology).

I have followed the build output instructions to put "homepage"="/slim" into the top-level package.json file. And after putting it in the /slim bucket folder, and routing 404s and index calls to /slim/index.html, it does work, but *only* if I launch it from a URL like https://hostname.example.com/studies/blah... (no /slim). You can see that the calls are really going to /slim, but the initial call cannot have /slim in it. If it does, then I get the static content, and then it stalls with a blank screen.

I have tried changing the "path" argument in the local.js from "/" to "/slim" and back, but it does not seem to have an effect.

**Comment by fedorov** [comment]
This appears to be the main roadblock for deploying slim in IDC, please mark this as priority.

**Comment by igoroctaviano** [comment]
Regarding /slim basename problem, in your bucket deploy yaml file have you tried this?
runtime: nodejs10
handlers:
  - url: /
    static_files: build/index.html
    upload: build/index.html
  - url: /slim
    static_files: build/index.html
    upload: build/index.html
  - url: /(.*)$
    static_files: build/\1
    upload: build/(.*)
adding another url to fallback to the index.html?
e.g. https://idc-external-006.uc.r.appspot.com/slim
i think updating react publicpath wont help since youre not using the webpack-dev server (edited)

**Comment by hackermd** [comment]
I've fixed the path configuration via 3e00c491fa4c8574bc769ddc9b4586957cb0258e, which will be included via #52. Note that I have updated the default local configuration to use this feature. When deploying the viewer together with the archive locally using the provided Docker compose configuration, the app will be located at `http://localhost:8008/viewer`.
