### ISSUE TITLE
Graceful handling of possible HTTP error status codes

### ISSUE THREAD

**Issue by wlongabaugh** [MGHComputationalPathology/slim#37]
When SliM is running against the IDC proxy, it is possible that it will receive an HTTP status return of 429, which means that the daily quota has been exceeded. To make this comprehensible to the user, it is preferable that the viewer redirects to a page explaining the error. In general, having an error handler has more general use. This is a snippet from the OHIF viewer configuration page to show how this is handled there:
 
```
  httpErrorHandler: error => {
    if (error.status == 429) {
      window.location = 'https://portal.example.com/quotaExceeded.html';
    }
 },
```

**Comment by Punzo** [comment]
@wlongabaugh we will implement this, could you please list all the error codes that you would like us to handle?

Implementation details:
1) we could have a json config file with declarative attributes: error, reinderict/messagge, url/text, etc....
2) but at the moment Slim should not give any API, extensions capabilities (out of scope), etc... therefore we will hardcode them directly in the source code.
3) implement a serviceLogger as interface to handle the errors.

**Comment by wlongabaugh** [comment]
The 429 resulting in a specified redirect is the only one we need implemented. The only other error handling we need is graceful backoff and retry if a 500 is returned from the server. If the proxy is idling along and then is suddenly overwhelmed with a flurry of requests and fails to keep up as it spools up new instances, it is possible to get 500s. Those should not bring everything to a grinding halt. Thanks.

**Comment by Punzo** [comment]
> The 429 resulting in a specified redirect is the only one we need implemented. The only other error handling we need is graceful backoff and retry if a 500 is returned from the server. If the proxy is idling along and then is suddenly overwhelmed with a flurry of requests and fails to keep up as it spools up new instances, it is possible to get 500s. Those should not bring everything to a grinding halt. Thanks.

thanks for the info Bill!

P.S.: I putting this in standy until we reach a consensus on the extendibility and configurability of Slim, see https://github.com/MGHComputationalPathology/slim/issues/42  and https://github.com/MGHComputationalPathology/slim/issues/44

**Comment by igoroctaviano** [comment]
> backoff and retry

Regarding backoff and retry, I recently added this feature to OHIF (for dicomweb-client only), now that It has the feature of adding request hooks. If this is needed here, it's worth creating a separate issue.
