### ISSUE TITLE
Delay in tile rendering

### ISSUE THREAD

**Issue by Punzo** [MGHComputationalPathology/slim#40]
from Steve: when zooming, sometimes some tiles are not rendered until there is another interaction (e.g. panning) and then they get rendered.

**Comment by Punzo** [comment]
@pieper I tried to reproduce this on several data, but I couldn't. I will try again, but if you could point the specific datasets and steps to reproduce, it would be great. Thanks!

**Comment by pieper** [comment]
I was able to reproduce with this dataset on mac with chrome.  Just panning and zooming for a few minutes got me to a spot where half the screen was blank for a long time (much more than the time it takes to fetch tiles)and when I finally panned the white section was filled in instantly (not enough time for another fetch).  So I still think there's a missing redraw in some cases.

If you still can reproduce I can show you on a screen share sometime.

https://dev-slim-viewer.canceridc.dev/studies/1.3.6.1.4.1.5962.99.1.2440258434.818002713.1625937929090.3.0/series/1.3.6.1.4.1.5962.99.1.2440258434.818002713.1625937929090.2.0

**Comment by Punzo** [comment]
ok thanks for the addtionalo info. I tried again and I could not reproduce. I am wondering if it is a GPU/OpenLayer/mac issue (I tested with chorme and nividia gpu on windows and linux). @hackermd could you please try to reproduce the issue?

**Comment by pieper** [comment]
I have reproduced twice, on different macs with chrome, one with AMD and one with Intel GPU.

**Comment by fedorov** [comment]
I was also able to reproduce. Is there a meaning for tiles being shown in pale color in the macro image in the bottom left? In the screenshot below, they stayed pale until I interacted panned in the viewer.

![image](https://user-images.githubusercontent.com/313942/126669000-e3cacf7d-ef87-469d-b610-2f0446624aaf.png)

**Comment by Punzo** [comment]
> I was also able to reproduce. 
are you also on mac? 

> Is there a meaning for tiles being shown in pale color in the macro image in the bottom left? In the screenshot below, they stayed pale until I interacted panned in the viewer.

no, probably is correlated to the same bug that Steve reported.

**Comment by Punzo** [comment]
in order to catch if it is an OpenLayer or Slim bug, @pieper @fedorov could you please try to reproduce the bug on this openLayer example? https://openlayers.org/en/latest/examples/overviewmap.html

It simply looks like the tiles get rendered a little bit before they are finished to be downloaded, but I really can't reproduce it on my system.

**Comment by pieper** [comment]
As far as I can tell it does not happen on the openlayers example.  Doing a similar amount of panning and zooming that results in the slim hang does not lead to a hang for openlayers.

**Comment by Punzo** [comment]
ok thanks for taking the time and testing. 

One thing that we can do easily is to update the OpenLayer version. Currently we are using 6.5.0 https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/blob/master/package.json#L70
while the latest version is 6.6.1 (the one of the examples). 

If still does not work, we would need to perfom deep debugging in the dicom-microscopy-viewer and openlayers.

**Comment by Punzo** [comment]
@pieper we updated the OpenLayer version in dicom-miscroscopy-viewer (https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/pull/57), as soon as https://github.com/MGHComputationalPathology/slim/pull/25 will be merged, we can release new versions of slim and dicom-miscroscopy-viewer and we can test this issue again.

P.S.: I tried to reproduce also on my linux laptop (with a Geforce 1050) and again I could not reproduce it ):

**Comment by pgundluru** [comment]
This issue still persists with Slim in prod. This was tested on chrome, safari on Mac workstation. When i click on SM, the tile is pale and blurred until i pan on the image in the viewer (try to zoom in)

**Comment by Punzo** [comment]
I still could not reproduce it, but this has an high probablity to be related to https://github.com/openlayers/openlayers/issues/12596 which was fixed in the recent OpenLayers release 6.7.0

I have opened a PR to update the dicom-microscopy-viewer:
https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/pull/65
