### ISSUE TITLE
Improve configuration for IDC deployment

### ISSUE THREAD

**Issue by fedorov** [MGHComputationalPathology/slim#42]
Slim is now available in the IDC dev tier, and there are some hopefully small configuration issues that would be good to resolve to avoid confusion, and make presentation consistent with the radiology viewer:
* annotations toolbar should be hidden, since this is a read-only view of the data
* study selector button should be disabled, since the user will get to the viewer from the portal
* IDC logo should be added as in OHIF viewer

**Comment by Punzo** [comment]
This probably is worth to discussing at the next meeting. we have two possibilities:

1) we fork Slim and we apply these modifications (I would avoid it)
2) we need a system in Slim to configure "extensions" (e.g. a config file) and refactor some parts. We were briefly discussing this yesterday for https://github.com/MGHComputationalPathology/slim/issues/37. The decision was to avoid to give any API/extensions capabilities for the moment, but in light of this, we should probably reconsider it.

P.S.: I would also put any work for https://github.com/MGHComputationalPathology/slim/issues/37 in standby until we take a decision on the extendibility and configurability of Slim.

**Comment by fedorov** [comment]
There's also this error that pops up every time on SM load, which would be good to eliminate.

![image](https://user-images.githubusercontent.com/313942/126809995-5a52d87e-cc63-4267-a343-1cb250c08ac0.png)

**Comment by fedorov** [comment]
@hackermd  - @wlongabaugh and most of the team feel strongly that the study list selector should be removed from the upper left corner. Can this be removed, if other items in the list cannot be addressed immediately?

**Comment by fedorov** [comment]
On that note, there is already a fork of Slim under IDC here https://github.com/ImagingDataCommons/slim that has a cherry-picked commit, so maybe for now we can make those customizations in the IDC fork, and then when the upstream is ready, synchronize the fork with the main repo? I am just thinking how we can expedite public release of Slim functionality, while not confusing the users with the items listed in this issue.

**Comment by hackermd** [comment]
> @wlongabaugh and most of the team feel strongly that the study list selector should be removed from the upper left corner before we can push the Slim capability into the user-facing production tier. Can this be removed, if other items in the list cannot be addressed immediately?

Yes, we can make this configurable easily. Will merge #47 later today and then start addressing these smaller issues.

**Comment by hackermd** [comment]
> On that note, there is already a fork of Slim under IDC here https://github.com/ImagingDataCommons/slim that has a cherry-picked commit, so maybe for now we can make those customizations in the IDC fork, and then when the upstream is ready, synchronize the fork with the main repo? I am just thinking how we can expedite public release of Slim functionality, while not confusing the users with the items listed in this issue.

I would avoid cherry picking into the fork if possible. I can prioritize this issue and make a new release within the next days.

**Comment by fedorov** [comment]
> I would avoid cherry picking into the fork if possible. 

I agree. @wlongabaugh did the cherry-picking into that fork to address #36 in absence of the solution in the master. We are aiming for production tier release around Wednesday next week. If a more robust solution can be ready in time that does not require cherry-picking, definitely we should use it.
