### ISSUE TITLE
Extendibility and Configurability

### ISSUE THREAD

**Issue by Punzo** [MGHComputationalPathology/slim#44]
For the moment we decided to avoid to give any API/extensions capabilities for Slim. However considering IDC issues 
1) https://github.com/MGHComputationalPathology/slim/issues/42
2) https://github.com/MGHComputationalPathology/slim/issues/37

maybe we should reconsider it.

**Comment by hackermd** [comment]
Closing this issue, since the features are already tracked by two separate issues (#37 and #42).
