### ISSUE TITLE
Handle errors upon attempt to load and parse annotations 

### ISSUE THREAD

**Issue by hackermd** [MGHComputationalPathology/slim#51]
When there are SR documents available that don't conform with the format expected by Slim, the viewer displays an error message.

![image](https://user-images.githubusercontent.com/313942/126809995-5a52d87e-cc63-4267-a343-1cb250c08ac0.png)

Not all errors may be worth bringing to the attention of the user. Let's try add checks to determine whether an existing SR does represent a displayable annotation.

**Comment by hackermd** [comment]
First reported by @fedorov in #42

**Comment by hackermd** [comment]
@wlongabaugh @fedorov as discussed this morning, I am not entirely sure what causes this error to be displayed. I've added a couple of additional checks of SR document content before attempting to extract annotations from the Measurement Report (see #58). Does this resolve the issue?

**Comment by wlongabaugh** [comment]
Testing your branch against the dev proxy is the best way to check if this solves the problem.

**Comment by hackermd** [comment]
This turned out to be an issue with the DICOMweb interface of either the Google Healthcare API or the proxy server.

If there was no match for the search transaction, the server responds with an empty HTML document instead of with a empty JSON array as specified by [DICOM Part 18 Section 10.6.3.3.3](http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_10.6.3.3.3.html).

<img width="231" alt="Screen Shot 2021-08-16 at 8 45 02 AM" src="https://user-images.githubusercontent.com/6855297/129565820-b955fa33-8cf2-492c-b613-ebfc155f1466.png">

In addition, the server erroneously responds with status code 200 instead of 204 as specified by [DICOM Part 18 Section 10.6.3.1](http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_10.6.3.html).

**Comment by hackermd** [comment]
The erroneous status code (200 instead of 204) seems to be caused by the proxy, because when accessing the Google Healthcare API directly a 204 status code is returned as expected.

The erroneous payload (`text/html` instead of `application/dicom+json`) seems to be an issue with the Google Healthcare API. I have reported the issue, but it may take some time until it will get fixed.

Of note, the dicomweb-client will ensure that an empty array is returned to the caller when a 204 status code is returned by the origin server.
