### ISSUE TITLE
Remote browser access error

### ISSUE THREAD

**Issue by DrexlerChao** [MGHComputationalPathology/slim#65]
Hi Sir,
After install Slim and upload DICOM successfully, the Slim localhost main page as follow,
![Screenshot from 2021-09-01 16-36-17](https://user-images.githubusercontent.com/27002631/131641630-9a918076-d017-4d90-b3c0-82ac83df28aa.png)

If we used remote browser to connect Slim,  it replied error message as follow,
![messageImage_1630484915959](https://user-images.githubusercontent.com/27002631/131641786-5d4144a8-8cf7-416d-ae32-563179a464f0.jpg)
![slim](https://user-images.githubusercontent.com/27002631/131641544-de0e1dad-c302-484d-ad4d-9e290b94d9e5.png)

Did we miss something that cause the error？

Your attention to this matter and prompt reply would be highly appreciated.
Thank you very much for your great help.

**Comment by hackermd** [comment]
It appears you didn't update the configuration accordingly. If you host the web application via a remote server, then the DICOMweb client running locally in your browser needs to access the remote DICOMweb server. Update either the `path` or the `url` parameter in your application configuration file (see [AppConfig.d.ts.](https://github.com/MGHComputationalPathology/slim/blob/75cc2a3497f293fe6b110e71d6daf3399adab2c4/src/AppConfig.d.ts#L62-L63).

**Comment by DrexlerChao** [comment]
@hackermd Dear Sir,
Thanks for your reply.

We try to use client computer to connect Slim viewer via web browser.
The computer IP and connection as follow,
![connect](https://user-images.githubusercontent.com/27002631/131809255-32d10a7e-ca2c-4ea4-8a95-037468bac9c7.png)

As you mentioned, update either the path or the url parameter in AppConfig.d.ts configuration file.
Here is our update procedure,
1. $ docker-compose down
2. Edit AppConfig.d.ts configuration file as follow,
![Screenshot from 2021-09-02 15-27-41](https://user-images.githubusercontent.com/27002631/131810555-1d710755-a657-45ed-ba9b-aad05fae566d.png)
3. $ docker-compose up -d

After restart Slim, the client web browser still unable to get the Slim viewer list.
Did we miss something during the update procedure?

**Comment by hackermd** [comment]
@DrexlerChao thank you for the detailed description!

Just for clarification, you shouldn't update the `AppConfig.d.ts` directly, but rather the application configuration file (see [Configuration section of README](https://github.com/MGHComputationalPathology/slim#configuration)). I just referenced the `AppConfig.d.ts` file to highlight the configuration options.

For example, you could create a `public/config/remote.js`, where the Slim viewer application would be located at `http://10.34.134.122:8008/` and the DICOMweb server would listen to `http://10.34.134.122:8008/dicomweb`:

```javascript
window.config = {
  path: "/",
  servers: [
    {
      id: "local",
      path: "/dicomweb",
      write: true
    }
  ],
  ...
};
```

**Comment by DrexlerChao** [comment]
@hackermd Dear Sir,
Thanks for your explain clearly and precisely.

We created a public/config/remote.js and edited it as follow,
![config](https://user-images.githubusercontent.com/27002631/131953238-c9ce9f6d-807c-4ab9-b9cc-f52228867a57.png)

After rebuild slim_app docker image and restart Slim viewer.
The client web browser can show the list and display SM image as follow,
![remote](https://user-images.githubusercontent.com/27002631/131953562-53b196fd-e3e0-43e9-8b3a-431ab7a33907.png)

Thank you very much for your great help.

**Comment by hackermd** [comment]
@DrexlerChao glad it's working.

**Comment by S-Streit** [comment]
Hmm kind of having the same issue. Treid to fix it by;
![image](https://user-images.githubusercontent.com/57636470/221910908-f116f3a0-1610-44ec-a3ca-228a57e423c8.png)
replacing localhost:8008 with the ip, which gets me past the first issue.
After this however:
![image](https://user-images.githubusercontent.com/57636470/221911358-e88a6ed6-aa45-43b9-8400-d06a48c30817.png)
Somwhere in fetching the image the Url gets replaced by localhost again.
Everything works if the Url is replaced by the ip
