### ISSUE TITLE
Deploy Slim on MAC

### ISSUE THREAD

**Issue by DrexlerChao** [MGHComputationalPathology/slim#66]
Dear Sir,
We try to deploy Slim on Apple MAC via Docker Compose.
Docker version is 20.10.8
Docker-Compose version is 1.29.2

After downloading dem4che, we try to build slim_app. But it did not work.
Here is error message,
![截圖 2021-09-03 下午3 36 38](https://user-images.githubusercontent.com/27002631/131971155-51f9b73c-3f66-4544-a348-806bcaa28672.png)

We try to reboot MAC and redeploy Slim. But it replied same error message.

We are not sure whether the MAC HW spec., OS version is sufficient for Slim.
Here is our MAC spec.
![截圖 2021-09-03 下午3 36 00](https://user-images.githubusercontent.com/27002631/131973411-5c7cc962-1760-4bac-b179-bea2fde897ff.png)

Did we miss something that cause the error？

**Comment by hackermd** [comment]
@DrexlerChao the  error message states that the build process ran out of memory. You may need to update your Docker preferences and increase the amount of memory.

**Comment by DrexlerChao** [comment]
@hackermd Dear Sir,
Thanks for your suggestion.

After updated Docker Preferences -> Resources -> ADVANCED -> Memory and Swap, we deployed Slim successfully.
![截圖 2021-09-06 上午10 34 47](https://user-images.githubusercontent.com/27002631/132154038-8276c7cc-c4ff-4dd6-8949-50dab60a61cf.png)
![截圖 2021-09-06 上午10 54 20](https://user-images.githubusercontent.com/27002631/132154562-c3dcb135-5b45-46ea-a996-6377122acd87.png)

Thanks for your great help.
