### ISSUE TITLE
Add "Debug info" and "About" features

### ISSUE THREAD

**Issue by fedorov** [MGHComputationalPathology/slim#68]
It would make sense to parallel those to what is available in OHIF. This would be good to resolve for the IDC production release. 

![image](https://user-images.githubusercontent.com/313942/133146645-21855f15-2fd9-4a7a-a68d-5e5b42414f97.png)

![image](https://user-images.githubusercontent.com/313942/133146672-cc0fb132-159d-4407-9718-2a582fcad91d.png)

@hackermd I do not have the permission to create new labels. When you get a chance, can you make "IDC:priority" label and assign it to this issue?

**Comment by hackermd** [comment]
The implementation of the debugging information should be straight forward. OHIF uses the [detect-browser](https://www.npmjs.com/package/detect-browser) package to get the information about the browser and operating system.

**Comment by hackermd** [comment]
Not yet super pretty, but the basic functionality is there.

<img width="599" alt="Screen Shot 2021-09-17 at 6 22 12 PM" src="https://user-images.githubusercontent.com/6855297/133859876-cb75a6e5-f8a5-4802-bf33-214348956e29.png">
