### ISSUE TITLE
Slim v0.3.0 blank main page

### ISSUE THREAD

**Issue by DrexlerChao** [MGHComputationalPathology/slim#73]
Dear Sir,

We downloaded the Slim latest version 0.3.0 and installed successfully.

After connected to the http://localhost:8008, the main page was blank as follow
![Screenshot from 2021-09-23 10-06-33](https://user-images.githubusercontent.com/27002631/134444918-41a1dcb4-a2ff-4889-a898-8b7840303de4.png)

Did we miss something that cause the error？

**Comment by hackermd** [comment]
I just realized that Create React App uses the [homepage](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#homepage) parameter in `package.json` to set `PUBLIC_URL` (see [here](https://create-react-app.dev/docs/deployment/#building-for-relative-paths) and [here](https://create-react-app.dev/docs/advanced-configuration/)).

I've added the `PUBLIC_URL` environment variable to the `Dockerfile`. That should resolve the issue.

**Comment by DrexlerChao** [comment]
@hackermd Dear Sir,

Yes. Slim v0.3.1 is working.
Thanks for your great help.
