### ISSUE TITLE
The endpoint /dicomweb does not work (locally) using docker compose

### ISSUE THREAD

**Issue by varikmp** [MGHComputationalPathology/slim#74]
Hello,

I followed the instruction to deploy Slim locally using docker compose without -d flag, and here is the output from console:

```
db_1    | 2021-09-26 18:28:00.363 UTC [35] ERROR:  relation "queue_msg" does not exist at character 8
db_1    | 2021-09-26 18:28:00.363 UTC [35] STATEMENT:  update queue_msg set msg_status=$1 where msg_status=$2 and queue_name=$3
app_1   | 2021/09/26 18:28:59 [error] 10#10: *3 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: slim, request: "GET /dicomweb/studies?ModalitiesInStudy=SM HTTP/1.1", upstream: "http://172.19.0.4:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies?ModalitiesInStudy=SM", host: "localhost:8008", referrer: "http://localhost:8008/"
app_1   | 2021/09/26 18:28:59 [error] 10#10: *3 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: 172.19.0.1, server: slim, request: "GET /dicomweb/studies?ModalitiesInStudy=SM HTTP/1.1", upstream: "http://172.19.0.4:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies?ModalitiesInStudy=SM", host: "localhost:8008", referrer: "http://localhost:8008/"
app_1   | 172.19.0.1 - - [26/Sep/2021:18:28:59 +0000] "GET /dicomweb/studies?ModalitiesInStudy=SM HTTP/1.1" 404 555 "http://localhost:8008/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" "-"
db_1    | 2021-09-26 18:29:33.040 UTC [39] ERROR:  relation "export_task" does not exist at character 41
db_1    | 2021-09-26 18:29:33.040 UTC [39] STATEMENT:  select exporttask0_.pk as col_0_0_ from export_task exporttask0_ where exporttask0_.device_name=$1 and exporttask0_.scheduled_time<current_timestamp and (exporttask0_.queue_msg_fk is null) limit $2
```

I tried to access http://localhost:8008/dicomweb but unfortunately, I got "404 Not Found" on the web page, and here is the output from console:

```
app_1   | 2021/09/26 21:00:54 [error] 10#10: *9 open() "/var/www/html/dicomweb" failed (2: No such file or directory), client: 172.19.0.1, server: slim, request: "GET /dicomweb HTTP/1.1", host: "localhost:8008"
app_1   | 172.19.0.1 - - [26/Sep/2021:21:00:54 +0000] "GET /dicomweb HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" "-"
```

I got in the slim_app docker container, but could not find dicomweb in /var/www/html. I am wondering if is there anything I did wrong in the deployment steps?

Best regards,

**Comment by hackermd** [comment]
Thanks for reporting the issue @varikmp.

> I followed the instruction to deploy Slim locally using docker compose without -d flag, and here is the output from console

Unfortunately, the output of the console is generally not very informative, since the DCM4CHEE application server doesn't write the application log messages to the standard error stream, but to the file `/opt/wildfly/standalone/log/server.log`.

```none
app_1   | 2021/09/26 18:28:59 [error] 10#10: *3 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: slim, request: "GET /dicomweb/studies?ModalitiesInStudy=SM HTTP/1.1", upstream: "http://172.19.0.4:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies?ModalitiesInStudy=SM", host: "localhost:8008", referrer: "http://localhost:8008/"
```
It seems the DICOMweb `/studies` request gets correctly proxied to `dcm4chee-arc/aets/DCM4CHEE/rs/studies`, but the connection timed out. I would recommend inspecting `/opt/wildfly/standalone/log/server.log`, which may provide further insight into why the DCM4CHEE server did not respond.

> I tried to access http://localhost:8008/dicomweb but unfortunately, I got "404 Not Found" on the web page

This is expected, since the `/` path does not represent a DICOMweb resource.  If you would like to test whether the DICOMweb API works, I would recommend using the `/studies` path (full URL: `http://localhost:8008/dicomweb/studies`).

**Comment by varikmp** [comment]
Hi @hackermd,

I am sorry for the late response. I have tried the **/studies** (full URL as you suggested) but saw nothing. I checked the server console and it said 

```
app_1   | 172.19.0.1 - - [03/Oct/2021:21:36:03 +0000] "GET /dicomweb/studies HTTP/1.1" 204 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" "-"
```

Also, here is the link to the **/opt/wildfly/standalone/log/server.log** that I got in the container:
```
https://drive.google.com/drive/u/0/folders/1BJnEH2mfd5rba5SM9FI9YH8jyw20-IV_
```
Thank you for your time.

**Comment by hackermd** [comment]
The fact that you get a `204` status code means that the origin server returned an empty response, i.e., that no data has been stored in the archive. See DICOM [PS 3.18 Section 8.5](http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_8.5.html#para_f9fb85ad-42cf-4d8a-a06e-e8f97791b0df).

**Comment by varikmp** [comment]
Does that mean the database-related errors reported in the console could be ignored and would not affect the empty response from the origin server?
```
db_1    | 2021-09-26 18:28:00.363 UTC [35] ERROR:  relation "queue_msg" does not exist at character 8
db_1    | 2021-09-26 18:29:33.040 UTC [39] ERROR:  relation "export_task" does not exist at character 41
```

**Comment by hackermd** [comment]
I don't know what causes these error messages. The database is part of the DCM4CHEE archive and I am not very familiar with its internals. If you continue to experience the issue, I would recommend reporting it at https://github.com/dcm4che/dcm4chee-arc-light/issues.

I am closing the issue, since it appears to be unrelated to the Slim application.
