### ISSUE TITLE
Slim 0.4.1 Service 'app' failed to build

### ISSUE THREAD

**Issue by DrexlerChao** [MGHComputationalPathology/slim#75]
Dear Sir,

We try to download the Slim latest version 0.4.1 and build the app image.
But we failed to build service 'app' as follow,
![Screenshot from 2021-10-20 16-55-02](https://user-images.githubusercontent.com/27002631/138062154-859d2830-3225-4fec-9349-48aec6be3113.png)

Did we miss something that cause the error?

**Comment by hackermd** [comment]
@DrexlerChao thanks for reporting the issue. Could you kindly try whether it works again [release 0.4.2](https://github.com/MGHComputationalPathology/slim/releases/tag/v0.4.2)?
