### ISSUE TITLE
Widgets for passing blending information to the viewer 

### ISSUE THREAD

**Issue by Punzo** [MGHComputationalPathology/slim#8]
The idea would be to have widgets similar to [link](http://avivator.gehlenborglab.org/?image_url=https://viv-demo.storage.googleapis.com/LuCa-7color_Scan1/):

![image](https://user-images.githubusercontent.com/7985338/98276343-1c94c780-1f96-11eb-813c-0ea5a758cb12.png)

for passing the color functions/blending parameters:

1. visibility
1. color
1. min and max
1. opacity

for each chosen channel (optical path) to the logic  (for ref: https://github.com/OHIF/Viewers/issues/2199)

**Comment by hackermd** [comment]
@Punzo as discussed, we want to implement the channel widgets in the right sider of the `SlideViewer` component.

The sider already contains a [Menu](https://ant.design/components/menu/#Menu) with a [Menu.SubMenu](https://ant.design/components/menu/#Menu.SubMenu) for "specimens" and "annotations". Let's add a submenu for "channels". The implementation of the channel list and individual channel items could be abstracted into `ChannelList` and `ChannelItem` components, respectively, similar to the already existing `AnnotationList` and `AnnotationItem`.

Each `ChannelItem` could contain a [Dropdown](https://ant.design/components/dropdown/) with a [Slider](https://ant.design/components/slider/) for selection threshold, opacity, etc.

**Comment by Punzo** [comment]
This has been addressed in https://github.com/MGHComputationalPathology/slim/pull/25 and https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/pull/54, Please @hackermd review

**Comment by hackermd** [comment]
This feature is available with version [0.2.0](https://github.com/MGHComputationalPathology/slim/releases/tag/0.2.0).
